# Generated by Django 5.2.1 on 2025-05-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinginfo',
            name='account_holder',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bankinginfo',
            name='account_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bankinginfo',
            name='account_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bankinginfo',
            name='ifsc_code',
            field=models.CharField(max_length=15),
        ),
    ]
